feat(carpool) : create carpool - UC-36
DUT-Info-Montreuil/SAE-5.A-carmate-back pull request #18
Opened 2023-12-01 09:19 UTC by ayman-75

2023-12-01 10:49 UTC, naulan-chrzaszcz requested changes
Revoir les tests unitaires
Deplacer du code de controller vers database
D'autre trucs que j'ai pas cité ici qu'il faut changer

Edit : Des conflics sur ta branche, pense a `git rebase develop`

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +    return True
Merci de lire cette parti: https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Back/blob/docs/docs/HOWTO.md#faire-un-repository

Les requêtes de la DB ne doit pas être ici

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +    return True
Merci de lire cette parti: https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Back/blob/docs/docs/HOWTO.md#faire-un-repository

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +        return jsonify({'error': str(e)}), 500
ChatGPT ?

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +def create_carpool():
```suggestion
def create_carpool_api():
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +carpool_blueprint = Blueprint("carpool", __name__, url_prefix="/carpool")
```suggestion
carpool = Blueprint("carpool", __name__, url_prefix="/carpool")
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +from database.exceptions import InvalidPrice
```suggestion
from datetime import datetime

from psycopg2 import errorcodes, connect
from psycopg2.errors import lookup
from flask import Blueprint, request, jsonify

from apiworker.carpool import CarpoolWorker
from api.worker.carpool.models.carpool_dto import CarpoolDTO
from database.repositories import establishing_connection, InternalServer, UniqueViolation
from database.exceptions import InvalidPrice
```
Si t'aurai suivi sont qu'on dissait, les imports ne se font pas n'importe comment

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +from database.exceptions import InvalidPrice
`InvalidPrice` c'est le worker
Lire: https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Back/blob/docs/docs/HOWTO.md#comprendre-la-traduction-et-les-differentes-couche-derreurs

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +        conn = connect(user="your_user", password="your_password", host="your_host", database="your_database")
```suggestion
        conn = establishing_connection()
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +        return jsonify({'message': 'Carpool created successfully', 'carpool_id': result.id}), 204
```suggestion
        return '', 204
```
`204` veut dire qu'il y a pas de contenu dans la requête
Lire: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

Soit tu renvoie un json qui possède le `carpool_id` avec une `200` soit une `204` avec rien du tout

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +        return jsonify({'error': str(e)}), 500
```suggestion
        abort(500)
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +            return jsonify({'error': 'All fields are required'}), 400
```suggestion
            return abort(400)
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +            return jsonify({'error': 'Invalid email format'}), 400
```suggestion
            return abort(400)
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +            return jsonify({'error': 'Invalid hour format'}), 400
```suggestion
            return abort(400)
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/controller/carpool/carpool_controller.py
> +            return jsonify({'error': 'Invalid location format'}), 400
```suggestion
            return abort(400)
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/worker/carpool/carpool_worker.py
> +        return self.carpool_repository.create_carpool(result)
A refactor, tu fait appel controller dans worker 
Je l'ai pas expliquer dans mon `HOWTO` mais worker c'est un genre de passerelle entre la DB et le Contrôler

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/worker/carpool/models/carpool_dto.py
> +    localisation_B: str
S'il y a une raison sur le fait que ca soit un string, normalement ca doit être un `float`

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/api/worker/carpool/models/carpool_dto.py
> +        return asdict(self)
Pas mal, je connais pas

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/database/exceptions.py
> +    pass
Ce n'est pas dans la DB mais dans le worker

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/database/repositories/carpool_repository.py
> +                 RETURNING id, start_hour, localisation_A, localisation_B, price, email"""
```suggestion
        query: str = f"""INSERT INTO carmate.{CarpoolRepository.POSTGRES_TABLE_NAME}
                                    VALUES (DEFAULT, %s, %s, %s, %s, %s) 
                                    RETURNING id, start_hour, localisation_A, localisation_B, price, email"""
```

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/database/repositories/carpool_repository.py
> +                    raise UniqueViolation(str(e))
Useless, ca arrivera jamais

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on src/database/schemas.py
> +    def to_self(_tuple: tuple) -> 'CarpoolTable':
C'est possible ca comme valeur de return

2023-12-01 10:49 UTC, naulan-chrzaszcz commented on test/carpool/test_carpool.py
Les tests ne passe pas dans la CI/CD de GitHub

2023-12-04 13:25 UTC, naulan-chrzaszcz commented
# Update
La maniere de codé les routes ne sont plus les même, lire :
- https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/blob/master/docs/HOWTO.md#creation-dune-route
- https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/blob/master/docs/HOWTO.md#ajouter-la-route-dans-le-fichier-mainpy

2023-12-23 11:51 UTC, naulan-chrzaszcz requested changes
J'ai juste survoler le code je ferai une review plus approfondi apres les changements

2023-12-23 11:51 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +    UserBannedRepositoryInterface, UserAdminRepositoryInterface, UserRepositoryInterface, TokenRepositoryInterface
```suggestion
from database.repositories import (
    CarpoolingRepositoryInterface,
    LicenseRepositoryInterface,
    UserBannedRepositoryInterface,
    UserAdminRepositoryInterface,
    UserRepositoryInterface,
    TokenRepositoryInterface
)
```

2023-12-23 11:51 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +class ZBI(Blueprint):
T'es ravagé

2023-12-23 11:51 UTC, naulan-chrzaszcz commented on src/api/controller/user/user.py
> +    UserAdminRepositoryInterface, LicenseRepositoryInterface
```suggestion
from database.repositories import (
    TokenRepositoryInterface,
    UserRepositoryInterface,
    UserBannedRepositoryInterface,
    UserAdminRepositoryInterface,
    LicenseRepositoryInterface
)
```

2023-12-23 11:51 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_carpooling.py
> +        print(departure_date_time)
J'ai l'impression que ta speedrun le create carpooling t_t

2023-12-23 11:51 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_carpooling.py
> +               price: float, departure_date_time: int) -> int:
```suggestion
    def worker(self,
               token: str,
               starting_point: List[float],
               destination: List[float],
               max_passengers: int,
               price: float,
               departure_date_time: int) -> int:
```

2023-12-23 11:51 UTC, naulan-chrzaszcz commented on test/carpooling/test_create_carpooling.py
> +    InMemoryDriverProfileRepository
```suggestion
from mock import (
    InMemoryCarpoolingRepository,
    InMemoryTokenRepository,
    InMemoryUserRepository,
    InMemoryDriverProfileRepository
)
```

2023-12-23 13:29 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +class ZBI(Blueprint):
ptdrrrrr j'ai oublié de renommer ça

2023-12-23 13:36 UTC, almerion commented on src/api/worker/carpooling/use_case/create_carpooling.py
> +        print(departure_date_time)
parceque j'ai oublié un print sur mon dernier force push ._.

2023-12-24 11:43 UTC, naulan-chrzaszcz requested changes
![COLOURBOX3461124](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/67024770/0ad577a3-92c2-49f3-9d8d-95831de163a3)
Voilà le cadeau de noel, une petite review

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
J'ai l'impression qu'on a besoin du `/` pour que cela fonctionne, j'pense enlève le préfixe pour le moment car c'est bizarre de faire comme ca

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +        self.token_and_driver_is_valid(token)
Tu peux le fourguer dans un `before_request`

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +            abort(400)
```suggestion
        try:
            starting_point = [float(i) for i in data["starting_point"]]
            destination = [float(i) for i in data["destination"]]
            max_passengers = int(data["max_passengers"])
            price = float(data["price"])
            departure_date_time = int(data["departure_date_time"])
        except ValueError:
            abort(400)
        except Exception:
            abort(500)
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +    def extract_token(self) -> str:
Fonction utilisé uniquement dans un seul endroit

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +            abort(403)
```suggestion
    def token_and_driver_is_valid(self):
        if request.authorization is None:
            abort(401)

        token = request.authorization.token
        if token is None:
            abort(401)
        
        user_infos: None | UserInformationDTO
        try:
            user_infos = CheckToken(self.token_repository,
                                    self.user_banned_repository,
                                    self.user_admin_repository,
                                    self.license_repository).worker(token)
        except Exception:
            abort(500)

        if not user_infos:
            abort(401)
        if user_infos.banned or not user_infos.driver:
            abort(403)
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/api/worker/auth/use_case/check_token.py
> +            driver_license_valid = driver_license.validation_status == ValidationStatus.Approved.name
```suggestion
        driver_license: LicenseTable
        driver_license_valid = False
        try:
            driver_license = self.license_repository.get_license_by_user_id(user.id, DocumentType.Driver.name)
        except Exception as e:
            raise InternalServerError(str(e))
        driver_license_valid = driver_license.validation_status == ValidationStatus.Approved.name
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_carpooling.py
> +            raise ValueError("Invalid departure date time")
Alors c'est cool, on fait les choses différemment
Le truc c'est qu'il faut ce mettre d'accord car ce genre de vérification je le fait dans le contrôleur 😬

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/exceptions.py
> +class CheckViolation(DatabaseError):
```suggestion
class ConstraintViolation(DatabaseError):
```
Plutôt ?

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +from database.exceptions import InternalServer, CheckViolation
```suggestion
from database.exceptions import InternalServer, ConstraintViolation
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                    raise CheckViolation("The starting point or end point is out of France bounds")
```suggestion
                    raise ConstraintViolation("The starting point or end point is out of France bounds")
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                    carpooling_id = curs.fetchone()
```suggestion
                carpooling_id = curs.fetchone()
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                    conn.commit()
```suggestion
```
Le block `with establishing_connection() as conn:` est sensé le faire automatiquement pour toi (à essayer)

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/license_repository.py
> +                    license_table = curs.fetchone()
```suggestion
                license_table = curs.fetchone()
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                    driver_profile = curs.fetchone()
```suggestion
                driver_profile = curs.fetchone()
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                    raise InternalServer(str(e))
```suggestion
                except ProgrammingError:
                    raise NotFound("driver not found")
                except IndexError:
                    raise NotFound("driver not found")
                except Exception as e:
                    raise InternalServer(str(e))
```

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/user_repository.py
> +                conn.close()
Mmmh, j'ai un doute sur le fait que je l'ai modifier dans ma PR #31

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on src/database/repositories/user_repository.py
> +                conn.close()
Idem, a checker et si c'est pas le cas -> edit

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/carpooling/test_create_carpooling.py
> +                carpooling_found = carpooling
Une fonction `get` serait pas mal pour `InMemoryCarpoolingRepository`

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/carpooling/test_create_carpooling.py
> +        self.driver_repository.driver_profiles.append(driver_profile)
Jpense qu'on a moyen de le fourger dans les InMemoryXxxXxxx pour mettre des données en plus dans leurs liste grâce aux `__init__()`
Faudra probablement faire une PR plus tard pour améliorer le constructeur des InMemoryXxxXxxx classes

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/mock/auth/in_memory_token_repository.py
> +    def __init__(self, user_repo=None, driver_repo=None):
```suggestion
    def __init__(self, user_repository=None, driver_repository=None):
```
Pour que ca soit uniforme avec les autre InMemoryXxxXxxx classes

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/mock/auth/in_memory_token_repository.py
> +        self.driver_repo = driver_repo
Idem here

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/mock/auth/in_memory_token_repository.py
> +                break
![COLOURBOX3461124](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/67024770/2fa6f0c8-284f-4030-925e-dac3a97182cc)

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/mock/auth/in_memory_token_repository.py
> +                break
![COLOURBOX3461124](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/67024770/36168fbb-6a5f-42f7-9e65-087c0f97c13c)

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/mock/auth/in_memory_token_repository.py
> +                break
![COLOURBOX3461124](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/67024770/da1913dc-c8db-47e4-a593-e2fe12c4a2bf)

2023-12-24 11:43 UTC, naulan-chrzaszcz commented on test/mock/carpooling/in_memory_carpooling_repository.py
> +            raise CheckViolation("Destination invalid")
```suggestion
        if not (41.3 <= starting_point[0] <= 51.1 and -5.142 <= starting_point[1] <= 9.561):
            raise ConstraintViolation("Starting_point invalid")

        if not (41.3 <= destination[0] <= 51.1 and -5.142 <= destination[1] <= 9.561):
            raise ConstraintViolation("Destination invalid")
```

2023-12-24 11:44 UTC, naulan-chrzaszcz commented
N'oublie pas de squash les commits de ayman par les tien
![maxresdefault](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/67024770/06177728-6cf9-4719-a44a-21a09d70321d)

2023-12-24 12:13 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +        self.token_and_driver_is_valid(token)
je l'ai sorti du before_request aprcequ'on a besoin du token dans le woker, ducoup ça ferait 2 fois l'extraction de token c'est pour ça que je l'ai sorti

2023-12-24 12:14 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
comment ça enlève le préfixe xD je comprends pas, j'enlève le préfixe et je met la route `/carpooling/`?

2023-12-24 12:19 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +    def extract_token(self) -> str:
pour éviter une double extraction mais je peux la sortir c'est comme tu le sens je suppose

2023-12-24 12:20 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +            abort(403)
si je fais comme ça on aura de la duplication avec l'extraction de token

2023-12-24 12:23 UTC, almerion commented on src/api/worker/auth/use_case/check_token.py
> +            driver_license_valid = driver_license.validation_status == ValidationStatus.Approved.name
Si tu except exception, tu vas catch le not found et faire une erreur si ça ne trouve pas le driver

2023-12-24 12:33 UTC, almerion commented on src/api/worker/carpooling/use_case/create_carpooling.py
> +            raise ValueError("Invalid departure date time")
On est sensé le mettre dans le métier pour pouvoir faire des tests dessus ... j'enlève ça et je dégage 60% de mes tests avec alors

2023-12-24 12:39 UTC, almerion commented on src/database/exceptions.py
> +class CheckViolation(DatabaseError):
C'est un Check violation, constraint violation c'est trop général il pourrait être appliqué partout

2023-12-24 12:45 UTC, almerion commented on src/database/repositories/user_repository.py
> +                conn.close()
C'est une méthode que ayman avait faite et qui existe déjà dans token repository... je delete ça

2023-12-24 12:49 UTC, almerion commented on src/database/repositories/user_repository.py
> +                conn.close()
idem, focntion de ayman je l'ai delete

2023-12-24 12:50 UTC, almerion commented on test/carpooling/test_create_carpooling.py
> +                carpooling_found = carpooling
La focntion n'existe pas dans le vrai répo donc je ne la metterai pas dans le mock, et le for c'est mieux qu'une fonction, on est jamais à l'abri qu'une fonction ait été faite par le cul. On n'utilise pas les fonctions du mock à part si c'est pour les tester, le reste ça se fait à la main

2023-12-24 12:51 UTC, almerion commented on test/carpooling/test_create_carpooling.py
> +        self.driver_repository.driver_profiles.append(driver_profile)
Yess, mais bon append ça tue personne

2023-12-24 12:57 UTC, almerion commented on test/mock/carpooling/in_memory_carpooling_repository.py
> +            raise CheckViolation("Destination invalid")
toujours non

2023-12-24 13:03 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
Regarde comment t'appelle ta route dans le front, c'est pas normal le `/` a la fin
https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-front/pull/21#pullrequestreview-1795560998

2023-12-24 13:06 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +        self.token_and_driver_is_valid(token)
La badababruh

2023-12-24 13:07 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
Bah je l'apelle /carpooling/ donc <prefix><route> -> /carpooling/

2023-12-24 13:08 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
T'es babage

2023-12-24 13:08 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
Je parle du slash a la fin

2023-12-24 13:09 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
Enleve le prefixe et laisse /carpooling pour la declaration de la route POST

2023-12-24 13:09 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
```suggestion
        super().__init__("carpooling_check", __name__)
                         
        self.route("/carpooling",
                   methods=["POST"])(self.create_route_carpooling_api)
```

2023-12-24 13:11 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
J'ai l'impression que tu dois mettre le slash a la fin comme tu dit ici :

> Bah je l'apelle /carpooling/ donc <prefix><route> -> /carpooling/

Mais dans beaucoup de routes qu'on a crée ben il y en a pas

2023-12-24 13:12 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
Je peux l'enlever au front ça ne change rien tu sais la route marche pareil

2023-12-24 13:13 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
Essaye de l'enlever côté front. Ca ma babage le cerveau

2023-12-24 13:13 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
Si ca marche pareil benef

2023-12-24 13:14 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +        self.token_and_driver_is_valid(token)
Il y a un bordel avec le check token, faudrait qu'on vois comment on peut simplifier cette merde

2023-12-24 13:14 UTC, almerion commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
ah non, enfin bon dans tous les cas c'est un problème au front pas au back ._.

2023-12-24 13:15 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
N'oublie pas a la fin de squash tous les commits en un https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/pull/18#issuecomment-1868497206

2023-12-24 13:17 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/with_driver_check.py
> +                   methods=["POST"])(self.create_route_carpooling_api)
> ah non, enfin bon dans tous les cas c'est un problème au front pas au back ._.

Bruh

2023-12-24 13:20 UTC, naulan-chrzaszcz approved these changes
LGTM !!!!!!!! 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2023-12-24 13:23 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_carpooling.py
> +            raise ValueError("Invalid departure date time")
> On est sensé le mettre dans le métier pour pouvoir faire des tests dessus ... j'enlève ça et je dégage 90% de mes tests avec alors

Bruh, j'ai tous mit dans le contrôleur ce genre de verif personne ma rien dit 🗿🗿

2023-12-24 13:24 UTC, merged