fix(search): fixed search for carpooling according to doc
DUT-Info-Montreuil/SAE-5.A-carmate-back pull request #37
Opened 2023-12-17 14:43 UTC by almerion

2023-12-17 15:11 UTC, naulan-chrzaszcz requested changes
Je comprend pas la raison d'enlever le `timestamp`, on va redevoir changer le code de mathéo... On peut toujours avoir la date sans prendre en compte l'heure...
Ca fait que tu mets des conditions en plus pour verifier si il y a une heures alors que datetime a probablement une fonction pour avoir uniquement l'heure du timestamp mit en argument d'URL

J'pense qu'il fallait juste ajuster la requête sql

2023-12-17 15:11 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> -                        AND departure_date_time >= to_timestamp(%s)
Mé ? 😒

2023-12-17 15:11 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> -                        AND departure_date_time >= to_timestamp(%s)
Pourquoi avoir enlever ca ?

2023-12-17 15:11 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                except ProgrammingError as e:
```suggestion
              except ProgrammingError:
```

2023-12-17 15:11 UTC, naulan-chrzaszcz commented
En soit c'est pas un fix mais un refactor car la route fonctionner de base

2023-12-17 15:13 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> -                        AND departure_date_time >= to_timestamp(%s)
Je peux le remettre mais ça plante ._.
pas besoin du to_timestamp

2023-12-17 15:13 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> -                        AND departure_date_time >= to_timestamp(%s)
parceque ça plante idem que celle du dessus

2023-12-17 15:14 UTC, almerion commented
Elle ne renvoyait pas les bonnes données et ne prennait pas les bonnes données en paramètre, un fix ducoup ..

2023-12-17 15:16 UTC, naulan-chrzaszcz commented
Ta rajouter un autre type de donnée a la route search c'est pas un fix

2023-12-17 15:24 UTC, naulan-chrzaszcz requested changes

2023-12-17 15:24 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                    LEFT JOIN carmate.{ReserveCarpoolingRepository.POSTGRES_TABLE_NAME} as r on (c.id = r.carpooling_id)
```suggestion
                    LEFT JOIN carmate.{self.POSTGRES_TABLE_NAME} as r on (c.id = r.carpooling_id)
```

2023-12-17 15:24 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                              per_page: int = 10) -> Tuple[int, List[CarpoolingForRecap]] | Tuple[int, List]: ...
Ca nique un peu les autres classe sur les valeurs retourné dans les fonctions de la classe repository ? C'est pas uniforme.
Qu'est-ce que t'en pense ?

2023-12-17 15:24 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                              per_page: int = 10) -> Tuple[int, List[CarpoolingForRecap]] | Tuple[int, List]: ...
Tous les autres fonctions des autres repository renvoie XxxxxTable

2023-12-17 15:24 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +                    LEFT JOIN carmate.{ReserveCarpoolingRepository.POSTGRES_TABLE_NAME} as r on (c.id = r.carpooling_id)
Bruh non c'est pas la bonne table 🗿

2023-12-17 15:26 UTC, naulan-chrzaszcz requested changes

2023-12-17 15:26 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/search.py
> +                else datetime.strptime(request.args.get('departure_date_time'), "%Y-%m-%d")
```suggestion
            departure_date_time = datetime.strptime(request.args.get('departure_date_time'), "%Y-%m-%dT%H:%M:%S" if "T" in request.args.get('departure_date_time') else "%Y-%m-%d")
```

2023-12-17 15:27 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/search.py
> +            print(e)
```suggestion
        except Exception:
```

2023-12-17 15:28 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +                              per_page: int = 10) -> Tuple[int, List[CarpoolingForRecap]] | Tuple[int, List]: ...
https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/blob/e19a9119574194b92587314ca96c3c38a8534cc4/src/database/repositories/license_repository.py#L24

Enfin après je peux toujours retourner le dto + une autre liste qui va associer carpooling_id & nb_places_reserves mais il y aura 3 select dans la fonction du coup

2023-12-17 15:35 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                              per_page: int = 10) -> Tuple[int, List[CarpoolingForRecap]] | Tuple[int, List]: ...
> https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/blob/e19a9119574194b92587314ca96c3c38a8534cc4/src/database/repositories/license_repository.py#L24

Effectivement tu souligne un problème d'uniformité que les précèdents reviewer sur la PR n'étais pas capable de le trouvé 👹👹👹

> Enfin après je peux toujours retourner le dto + une autre liste qui va associer carpooling_id & nb_places_reserves mais il y aura 3 select dans la fonction du coup et le worker devra les mapper entre eux

Après c'est pas obliger, c'est qu'une suggestion

2023-12-17 15:45 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +                              per_page: int = 10) -> Tuple[int, List[CarpoolingForRecap]] | Tuple[int, List]: ...
très franchement moi ça me change rien de rien je le laisserait comme ça si c'était moi alors c'est comme tu le sens

2023-12-17 15:46 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +                              per_page: int = 10) -> Tuple[int, List[CarpoolingForRecap]] | Tuple[int, List]: ...
Si on voulait faire bien on devrait retourner aucune table mais que des dto de la db mais actuellement on renvoie que des tables

2023-12-17 15:51 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                              per_page: int = 10) -> Tuple[int, List[CarpoolingForRecap]] | Tuple[int, List]: ...
Si c'est déjà fait sur la fonction `get_license_not_validated`, j'peux rien dire, laisse comme ca du coup

2023-12-17 16:10 UTC, naulan-chrzaszcz requested changes
Des ajustements:
- La page 0 existe
- Code style
- Le `worker` de `get_route_carpoolings` n'est pas bien nettoyer

Des modifications injustifié:
![rock-one-eyebrow-raised-rock-staring](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/67024770/c70748db-d390-48d1-8296-0f846bbaac7a)
- J'ai besoin d'explication sur le fait d'avoir mit `datetime`, est-ce vraiment utile et pourquoi ? 
- Comment ta fait pour que ça plante ?
- Ta demandé a Mathéo si ça va pas niquer son code ?

2023-12-17 16:10 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/search.py
>  from api.worker.carpooling.models import CarpoolingDTO
```suggestion

from api.worker.carpooling.models import CarpoolingDTO
```

2023-12-17 16:10 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/search.py
> +from datetime import datetime
```suggestion
from datetime import datetime

```

2023-12-17 16:10 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/get_route_carpoolings.py
> -                [CarpoolingDTO.from_table(carpooling_table) for carpooling_table in carpoolings_data[1]])
Il y a un problème

2023-12-17 16:10 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/get_route_carpoolings.py
>          carpoolings_data: Tuple[int, List[CarpoolingTable]]
```suggestion
```

2023-12-17 16:10 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/get_route_carpoolings.py
>                 page: int | None = None) -> Tuple[int, List[CarpoolingDTO]]:
```suggestion
               page: int | None = None) -> Tuple[int, List[CarpoolingTable]]:
```

2023-12-17 16:10 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                              departure_date_time: datetime,
```suggestion
                              departure_date_time: int,
```

2023-12-17 16:16 UTC, naulan-chrzaszcz commented
https://www.unixtimestamp.com/

2023-12-18 18:54 UTC, almerion commented
> Des ajustements:
> 
> * La page 0 existe
> * Code style
> * Le `worker` de `get_route_carpoolings` n'est pas bien nettoyer
> 
> Des modifications injustifié: ![rock-one-eyebrow-raised-rock-staring](https://private-user-images.githubusercontent.com/67024770/291075917-c70748db-d390-48d1-8296-0f846bbaac7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjU4NTIsIm5iZiI6MTcwMjkyNTU1MiwicGF0aCI6Ii82NzAyNDc3MC8yOTEwNzU5MTctYzcwNzQ4ZGItZDM5MC00OGQxLTgyOTYtMGY4NDZiYmFhYzdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZDYxZmEzMTE5ZmYwYjJkZTc2ZTQ3NzM3NzA1MTA0MDBjYjRmYjY0NWQ5NjY1NDQwNTNlZmRhY2I3NzRmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzZIwse7roT7TipWeJdmK80oDWL8dW9B7B5Z0mq83Go) [ ](https://private-user-images.githubusercontent.com/67024770/291075917-c70748db-d390-48d1-8296-0f846bbaac7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjU4NTIsIm5iZiI6MTcwMjkyNTU1MiwicGF0aCI6Ii82NzAyNDc3MC8yOTEwNzU5MTctYzcwNzQ4ZGItZDM5MC00OGQxLTgyOTYtMGY4NDZiYmFhYzdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZDYxZmEzMTE5ZmYwYjJkZTc2ZTQ3NzM3NzA1MTA0MDBjYjRmYjY0NWQ5NjY1NDQwNTNlZmRhY2I3NzRmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzZIwse7roT7TipWeJdmK80oDWL8dW9B7B5Z0mq83Go) ![rock-one-eyebrow-raised-rock-staring](https://private-user-images.githubusercontent.com/67024770/291075917-c70748db-d390-48d1-8296-0f846bbaac7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjU4NTIsIm5iZiI6MTcwMjkyNTU1MiwicGF0aCI6Ii82NzAyNDc3MC8yOTEwNzU5MTctYzcwNzQ4ZGItZDM5MC00OGQxLTgyOTYtMGY4NDZiYmFhYzdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZDYxZmEzMTE5ZmYwYjJkZTc2ZTQ3NzM3NzA1MTA0MDBjYjRmYjY0NWQ5NjY1NDQwNTNlZmRhY2I3NzRmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzZIwse7roT7TipWeJdmK80oDWL8dW9B7B5Z0mq83Go) [ ](https://private-user-images.githubusercontent.com/67024770/291075917-c70748db-d390-48d1-8296-0f846bbaac7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjU4NTIsIm5iZiI6MTcwMjkyNTU1MiwicGF0aCI6Ii82NzAyNDc3MC8yOTEwNzU5MTctYzcwNzQ4ZGItZDM5MC00OGQxLTgyOTYtMGY4NDZiYmFhYzdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZDYxZmEzMTE5ZmYwYjJkZTc2ZTQ3NzM3NzA1MTA0MDBjYjRmYjY0NWQ5NjY1NDQwNTNlZmRhY2I3NzRmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzZIwse7roT7TipWeJdmK80oDWL8dW9B7B5Z0mq83Go)
> 
> * J'ai besoin d'explication sur le fait d'avoir mit `datetime`, est-ce vraiment utile et pourquoi ?
> * Comment ta fait pour que ça plante ?
> * Ta demandé a Mathéo si ça va pas niquer son code ?

J'ai juste suivi la doc, si son code plante c'est que la doc n'a pas été suivie je suppose ._.
Mais ça plante pas ._.

2023-12-18 19:31 UTC, naulan-chrzaszcz requested changes
Il y a deux trucs qui ont été mit en "resolve" mais rien n'a changé
 - https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/pull/37#discussion_r1429197607

2023-12-18 19:33 UTC, almerion commented
> Il y a deux trucs qui ont été mit en "resolve" mais rien n'a changé
> 
> * [fix(search): fixed search for carpooling according to doc #37 (comment)](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/pull/37#discussion_r1429197607)
> * [fix(search): fixed search for carpooling according to doc #37 (comment)](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/pull/37#discussion_r1429197800)

aucun des deux est en resolve

2023-12-18 19:47 UTC, naulan-chrzaszcz requested changes
N'oublie pas de squash les commits et puis on est good

2023-12-18 19:47 UTC, naulan-chrzaszcz commented on test/mock/carpooling/in_memory_carpooling_repository.py
> +        filtered_carpoolings = copy.deepcopy([
`deepcopy`?

2023-12-18 20:05 UTC, naulan-chrzaszcz approved these changes

2023-12-18 20:54 UTC, merged