feat(review): create review
DUT-Info-Montreuil/SAE-5.A-carmate-back pull request #41
Opened 2023-12-29 16:47 UTC by almerion

2023-12-29 18:19 UTC, naulan-chrzaszcz requested changes
Beaucoup beaucoup de code style et de simplification de code

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +        return CarpoolingTable.to_self(*carpooling)
```suggestion
        return CarpoolingTable(*carpooling)
```
Voir #40

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/review_reposiotry.py
> +        """
```suggestion
        query = f"""
                INSERT INTO {self.POSTGRES_TABLE_NAME}(passenger_id, 
                                                       driver_id, 
                                                       economic_driving_rating, 
                                                       safe_driving_rating, 
                                                       sociability_rating, 
                                                       review) 
                VALUES (%s, %s, %s, %s, %s, %s)
        """
```
C'est pas obligé

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/review_reposiotry.py
> +                                 )
```suggestion
                    curs.execute(query, (passenger_id,
                                         review.driver_id,
                                         review.economic_driving_rating,
                                         review.safe_driving_rating,
                                         review.sociability_rating,
                                         review.review))
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +from database.schemas import UserTable, TokenTable, DriverProfileTable, PassengerProfileTable
```suggestion
from database.repositories import (
    UserRepository,
    DriverProfileRepository,
    PassengerProfileRepository
)
from database.schemas import (
    UserTable,
    TokenTable,
    DriverProfileTable,
    PassengerProfileTable
)
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                    WHERE tkn.token=%s"""
```suggestion
        query = f"""
            SELECT passenger.*
            FROM carmate.{self.POSTGRES_TABLE_NAME} tkn
            INNER JOIN carmate.{UserRepository.POSTGRES_TABLE_NAME} usr 
                ON tkn.user_id=usr.id
            INNER JOIN carmate.{PassengerProfileRepository.POSTGRES_TABLE_NAME} passenger 
                ON usr.id=passenger.user_id
            WHERE tkn.token=%s
        """
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +        return PassengerProfileTable.to_self(passenger_profile)
```suggestion
        return PassengerProfileTable(*passenger_profile)
```
Voir #40

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +
```suggestion
            if passenger_profile is None:
                raise NotFound("passenger not found")
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/schemas.py
> +        )
```suggestion
```
Voir #40

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/main.py
>          if os.getenv("API_MODE") == "PROD":
```suggestion
        self.api.register_blueprint(ReviewRoutes())
        
        if os.getenv("API_MODE") == "PROD":
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/auth/in_memory_token_repository.py
> +from database.schemas import TokenTable, UserTable, DriverProfileTable, PassengerProfileTable
```suggestion
from database.schemas import (
    TokenTable,
    UserTable,
    DriverProfileTable,
    PassengerProfileTable
)
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/auth/in_memory_token_repository.py
> +                break
Fait une version sans `break` par pitier 🙏🙏🙏, tu me fait une Ayman là 👹🤙

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/auth/in_memory_token_repository.py
> +        return found_passenger
```suggestion
        if found_passenger is None:
            raise NotFound("passenger not found")
        return found_passenger
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/carpooling/in_memory_carpooling_repository.py
> +                        reserve_carpooling.canceled is False:
```suggestion
                if reserve_carpooling.user_id == user_id 
                        and reserve_carpooling.carpooling_id == carpooling.id \
                        and reserve_carpooling.passenger_code_validated \
                        and not reserve_carpooling.canceled:
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/carpooling/in_memory_carpooling_repository.py
> +        return sorted_carpooling_list[0]
```suggestion
        if len(filtered_carpooling_list) == 0:
            raise NotFound("There are no carpooling existing between these two users")
        return sorted(filtered_carpooling_list, key=lambda x: x.departure_date_time, reverse=True)[0]
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/carpooling/in_memory_review_repository.py
> +            if self_review.driver_id == review.driver_id and self_review.user_id == user_id:
```suggestion
            if self_review.driver_id == review.driver_id \
                    and self_review.user_id == user_id:
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on test/carpooling/test_create_review.py
> +from hashlib import sha512
```suggestion
import random
import unittest

from datetime import datetime, timedelta
from hashlib import sha512
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on test/carpooling/test_create_review.py
> +    PassengerProfileTable
```suggestion
from api.worker import AccountStatus
from api.worker.carpooling.models import ReviewDTO
from api.worker.carpooling.use_case import CreateReview
from api.exceptions import (
    UserNotFound,
    CarpoolingNotFound,
    CarpoolingReviewTimeExpiredException,
    PassengerNotFound
)
from database.schemas import (
    CarpoolingTable,
    ReserveCarpoolingTable,
    UserTable,
    TokenTable,
    ReviewTable,
    PassengerProfileTable
)
from database.exceptions import UniqueViolation
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/review.py
> +from api.worker.carpooling.models.review_dto import ReviewDTO
```suggestion
from api.worker.carpooling.models import ReviewDTO
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/review.py
> +from api.worker.carpooling.use_case.create_review import CreateReview
```suggestion
from api.worker.carpooling.use_case import CreateReview
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_review.py
> +from database.schemas import CarpoolingTable, PassengerProfileTable
```suggestion
from api.worker import Worker
from api.worker.carpooling.models import ReviewDTO
from api.exceptions import (
    CarpoolingNotFound,
    InternalServerError,
    CarpoolingReviewTimeExpiredException,
    PassengerNotFound
)
from database.schemas import CarpoolingTable, PassengerProfileTable
from database.exceptions import NotFound
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_review.py
> +            last_carpooling = self.carpooling_repository.get_last_carpooling_between(review.driver_id, passenger.user_id)
Juste tu peux m'expliquer le choix du nom de la fonction ?

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/review_reposiotry.py
> +from database.exceptions import UniqueViolation, InternalServer
```suggestion
from abc import ABC

from psycopg2 import errorcodes
from psycopg2.errors import lookup

from api.worker.carpooling.models import ReviewDTO
from database import establishing_connection
from database.exceptions import UniqueViolation, InternalServer
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/database/repositories/review_reposiotry.py
> +               review: ReviewDTO, passenger_id: int): ...
```suggestion
    def insert(self,
               review: ReviewDTO, 
               passenger_id: int): ...
```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/main.py
> +from api.controller.carpooling.review import ReviewRoutes
```suggestion
```
Tous est importé grâce a la ligne de dessus
Check t'es declaration dans `__init__.py` si ta pas accèes a `ReviewRoutes` via l'import `from api.controller import *`

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/auth/in_memory_token_repository.py
>  from database.exceptions import *
C'est grossier, ta pas besoin de tous

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/auth/in_memory_token_repository.py
> +
```suggestion

```

2023-12-29 18:19 UTC, naulan-chrzaszcz commented on src/mocks/carpooling/in_memory_review_repository.py
> +from database.schemas import ReviewTable
```suggestion
from database.repositories import ReviewRepositoryInterface
from database.schemas import ReviewTable
from database.exceptions import UniqueViolation
```

2023-12-29 18:22 UTC, naulan-chrzaszcz commented
Revoir le nom du commit et corrigé les fautes d'anglais si il y en a

Nouveau nom : `feat(review): create carpoolings reviews routes - UC-42`

2023-12-29 18:48 UTC, almerion commented on src/api/worker/worker.py
> +    def worker(self, *args, **kwargs):
```suggestion
    def worker(self):
```

2023-12-29 18:50 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +    BookingCarpoolingRepositoryInterface
Non c'est moi qui ait fait ça et c'est bon parceque sinon :
![image](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/95338528/730f9710-86a4-4c13-923b-f5ece914f251)

2023-12-29 18:52 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +        """
franchement je merge ça parceque j'ai pas envie de me casser la tête mais jamais tu verras une requête sql faite comme ça

2023-12-29 18:52 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +        """
c'est affreux mais amen

2023-12-29 18:54 UTC, almerion commented on src/database/repositories/review_reposiotry.py
> +        """
idem dégeulasse mais je veux pas me casser le crane

2023-12-29 18:56 UTC, almerion commented on src/database/repositories/token_repository.py
> +                    WHERE tkn.token=%s"""
idem

2023-12-29 18:58 UTC, almerion commented on src/mocks/auth/in_memory_token_repository.py
> +                break
C'est pour que ça aille plus vite mais soit, on va faire toute la liste c'est pas grave j'ai aucune envie de faire un while

2023-12-29 18:59 UTC, almerion commented on src/mocks/auth/in_memory_token_repository.py
> +                break
```suggestion
```

2023-12-29 19:05 UTC, almerion commented on src/api/worker/carpooling/use_case/create_review.py
> +            last_carpooling = self.carpooling_repository.get_last_carpooling_between(review.driver_id, passenger.user_id)
bah get le dernier carpooling entre le driver et l'user avec les id

2023-12-29 19:06 UTC, almerion commented on src/mocks/auth/in_memory_token_repository.py
>  from database.exceptions import *
Sisi, on a besoin de tout ça dans le fichier

2023-12-29 19:46 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_review.py
> +            last_carpooling = self.carpooling_repository.get_last_carpooling_between(review.driver_id, passenger.user_id)
Okay

2023-12-29 19:49 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +    BookingCarpoolingRepositoryInterface
Tu peux pas deplacer certain from dans le `__init__.py` de repositories pour plus avoir cet erreur ?

2023-12-29 19:50 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +    BookingCarpoolingRepositoryInterface
Ou ta déjà essayé ?

2023-12-29 19:57 UTC, almerion commented on src/database/repositories/carpooling_repository.py
> +    BookingCarpoolingRepositoryInterface
déjà essayer ça plante peu importe ou il se trouve

2023-12-30 12:53 UTC, naulan-chrzaszcz requested changes
![img](https://image.noelshack.com/fichiers/2017/07/1487382298-risitasdepressif.png)

2023-12-30 12:53 UTC, naulan-chrzaszcz commented on src/api/exceptions.py
> +class CarpoolingReviewTimeExpiredException(Exception):
Est-ce vraiment utile de répété Exception ?
Les autres classes qui lève des exceptions on pas de suffix Exception

2023-12-30 12:53 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                raise NotFound("passenger not found")
```suggestion
        if passenger_profile is None:
            raise NotFound("passenger not found")
```
Au même niveau que le return (je l'ai mal placé sur la dernière review)

2023-12-30 12:53 UTC, naulan-chrzaszcz commented on src/mocks/auth/in_memory_token_repository.py
> +                break
![img](https://image.noelshack.com/fichiers/2017/07/1487382298-risitasdepressif.png)

2023-12-30 12:53 UTC, naulan-chrzaszcz commented on src/mocks/auth/in_memory_token_repository.py
> +                break
![img](https://image.noelshack.com/fichiers/2017/07/1487382298-risitasdepressif.png)

2023-12-30 12:53 UTC, naulan-chrzaszcz commented on src/mocks/carpooling/in_memory_carpooling_repository.py
> +                    break
![img](https://image.noelshack.com/fichiers/2017/07/1487382298-risitasdepressif.png)

2023-12-30 12:54 UTC, almerion commented on src/api/exceptions.py
> +class CarpoolingReviewTimeExpiredException(Exception):
```suggestion
class CarpoolingBookedTooLate():
    def __init__(self, message="departure time of carpooling is already passed"):
        super().__init__(message)


class CarpoolingReviewTimeExpiredException(Exception):
```

2023-12-30 12:55 UTC, almerion commented on src/mocks/auth/in_memory_token_repository.py
> +                break
```suggestion
```

2023-12-30 12:57 UTC, almerion commented
![image](https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/assets/95338528/f6cea2f3-0c23-48c7-b115-84ba3b159bd8)

2023-12-30 12:57 UTC, almerion commented
j'y touche pluy moi ça commence à me rendre fou

2023-12-30 12:58 UTC, naulan-chrzaszcz commented
Bruh ta fait cash je delete le break
![img](https://image.noelshack.com/fichiers/2017/07/1487382298-risitasdepressif.png)

2023-12-30 13:01 UTC, naulan-chrzaszcz commented
Regarde les `next` en Python c'est pas mal

2023-12-30 13:04 UTC, naulan-chrzaszcz commented
L'assistant me propose ca et c'est plutôt pas mal :
```python
found_user = next((user for user in self.user_repository.users if found_token.user == user.id), None)
```

2023-12-30 13:07 UTC, naulan-chrzaszcz commented
> j'y touche pluy moi ça commence à me rendre fou

https://www.tiktok.com/@kid.jey/video/7174886745886985477?is_from_webapp=1&sender_device=pc

2024-01-04 17:04 UTC, naulan-chrzaszcz commented on src/api/exceptions.py
> +class CarpoolingReviewTimeExpiredException(Exception):
Ah ouais j'avais pas vu mais ta rien compris @almerion 🚀🚀🚀🚀

2024-01-04 17:04 UTC, naulan-chrzaszcz commented on src/api/exceptions.py
> +class CarpoolingReviewTimeExpiredException(Exception):
C'est pour ca que t'avais cet erreur https://github.com/DUT-Info-Montreuil/SAE-5.A-carmate-back/pull/41#issuecomment-1872523214
Complètement ravagax 🚀🚀🚀🚀🚀🚀

2024-01-04 17:08 UTC, naulan-chrzaszcz approved these changes
LGTM !!!!!!!!!!! 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2024-01-04 19:47 UTC, merged