feat(history): add users carpoolings done history routes - UC-28
DUT-Info-Montreuil/SAE-5.A-carmate-back pull request #44
Opened 2024-01-03 09:15 UTC by naulan-chrzaszcz

2024-01-04 19:52 UTC, almerion requested changes

2024-01-04 19:52 UTC, almerion commented on src/api/worker/user/use_case/get_history.py
> +            raise e
On appelle pas un worker dans un worker et ça sert a rien de except e pour raise e enlève le try catch ça fait la même chose

2024-01-04 19:52 UTC, almerion commented on src/api/worker/user/use_case/get_history.py
> +            carpoolings_done = self.booking_carpooling_repository.done_from_user_id(user.id)
On choppe que ceux qui ont été faits, ceux qui ont été annulés ou juste jamais confirmé on les prends pas ?

2024-01-04 19:52 UTC, almerion commented on src/database/repositories/booking_carpooling_repository.py
> +            WHERE passenger_code_validated=true
ça marche avec true comme ça ? j'ai toujours fait avec 't' je ne sais même pas si ça marche

2024-01-04 20:18 UTC, naulan-chrzaszcz commented on src/api/worker/user/use_case/get_history.py
> +            raise e
Pourquoi réinventer la roue ?

2024-01-04 20:19 UTC, naulan-chrzaszcz commented on src/api/worker/user/use_case/get_history.py
> +            raise e
Pour le `try` `except` ouaip je peux l'enlever

2024-01-04 20:35 UTC, naulan-chrzaszcz commented on src/database/repositories/booking_carpooling_repository.py
> +            WHERE passenger_code_validated=true
En prod, ça fonctionne

2024-01-04 20:46 UTC, almerion commented on src/database/repositories/booking_carpooling_repository.py
> +            WHERE passenger_code_validated=true
okay nice, je metterais true les prochaines fois c'est mieux que 't'

2024-01-04 20:47 UTC, almerion commented on src/api/worker/user/use_case/get_history.py
> +            raise e
Yess, vaut mieux rapeller le repo, dans un worker il faut pas apeller des worker, normalement on peux call les répo ou des services mais pas d'autres worker

2024-01-09 10:38 UTC, naulan-chrzaszcz commented on src/api/worker/user/use_case/get_history.py
> +            carpoolings_done = self.booking_carpooling_repository.done_from_user_id(user.id)
Ceux qui on passenger_code_validated a True

2024-01-10 15:31 UTC, almerion commented
Page `/subscriptions`(passenger) pour visualiser tous les abonnements crées
Pour chaque abonnement afficher les infos :
- adresse départ
- adresse arrivée
- range de l'abonnement
- label
- heure départ
- Jours
Pour chaque abonnement `afficher les covoiturages réservés automatiquements`:
- Full DTO

2024-01-16 15:49 UTC, naulan-chrzaszcz commented
- /history/carpooling/booked
- /history/schedule-carpooling/booked
- /history/carpooling/published
- /history/schedule-carpooling/published

2024-01-17 21:18 UTC, almerion approved these changes

2024-01-17 23:02 UTC, merged