refactor(profiles): add in Profiles DTO's the profile picture
DUT-Info-Montreuil/SAE-5.A-carmate-back pull request #45
Opened 2024-01-03 12:12 UTC by naulan-chrzaszcz

2024-01-05 20:37 UTC, almerion requested changes
Petit problème au niveau des retour des fonctions + des cast

2024-01-05 20:37 UTC, almerion commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
DriverProfileDTO plutôt non ?

2024-01-05 20:37 UTC, almerion commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
idem ici

2024-01-05 20:37 UTC, almerion commented on src/database/repositories/passenger_profile_repository.py
> +        return PassengerProfileTable(*passenger_data[:-1]), passenger_data[-1]
idem PassengerProfileDTO

2024-01-05 20:37 UTC, almerion commented on src/database/repositories/passenger_profile_repository.py
> +        return PassengerProfileTable(*passenger_data[:-1]), passenger_data[-1]
idem

2024-01-05 20:37 UTC, almerion commented on src/mocks/user/in_memory_driver_profile_repository.py
> +                return driver, profile_picture
cast en object DriverProfileDTO ou change le type de retour, le type de retour est à changer sur la fonction aussi  c'est pas driverProrfileTable

2024-01-05 20:37 UTC, almerion commented on src/mocks/user/in_memory_passenger_profile_repository.py
> +                return passenger, profile_picture
idem ici que pour le driver

2024-01-07 23:02 UTC, naulan-chrzaszcz commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
Avec réflexion, si tu regarde bien le code c'est voulu comme ça
C'est fait exprès
Dans le `worker`, je le converti en `DriverProfileDTO`

2024-01-07 23:04 UTC, naulan-chrzaszcz commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
Vu qu'on est dans le repository, je ne renvoi pas de DTO
L'autre fois je t'avais fait une remarque car je me disais que c'étais pas good de renvoyé un DTO dans le repository car le DTO est côté API et non côté Database

2024-01-07 23:05 UTC, naulan-chrzaszcz commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
Il y a des exceptions ailleurs dans le code (qu'on a vu plus tard) où il y a des renvois de DTO a la place d'une table

2024-01-08 09:58 UTC, naulan-chrzaszcz commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
(J'ai fait aussi en sorte de faire le min de modification)

2024-01-08 12:37 UTC, LiberiBg requested changes

2024-01-08 12:38 UTC, naulan-chrzaszcz commented on src/api/worker/user/models/driver_profile_dto.py
> +
```
scoreSociability
scoreEconomicalDriving
scoreSafeDriving
nbr_rating
```
C'est #46

2024-01-08 12:38 UTC, almerion commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
ah oui j'avais pas vu la parenthese fermée mybad, mais du coup c'est le type de retour de la fonction qu'il faut changer

2024-01-08 12:41 UTC, naulan-chrzaszcz commented on src/api/worker/user/models/driver_profile_dto.py
> +
Ou bien sinon c'est vraiment dans cette PR le score du profil

2024-01-08 12:41 UTC, almerion commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
dans l'interface et le mock

2024-01-08 12:41 UTC, almerion commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
pour les deux je crois

2024-01-08 12:48 UTC, naulan-chrzaszcz commented on src/database/repositories/driver_profile_repository.py
> +        return DriverProfileTable(*driver_data[:-1]), driver_data[-1]
Ouaip je viens de corrigé

2024-01-08 12:49 UTC, naulan-chrzaszcz commented on src/api/worker/user/models/driver_profile_dto.py
> +
Cette PR concerne l'ajout de la photo de profil dans le DTO, je fait ce que tu ma dit dans une autre PR

2024-01-09 16:56 UTC, almerion approved these changes
lgtm 🚀🚀🚀🚀🚀🚀🚀🚀

2024-01-09 18:51 UTC, merged