feat(scoreboard): add listings of best drivers accordings to criterion - UC-44
DUT-Info-Montreuil/SAE-5.A-carmate-back pull request #46
Opened 2024-01-05 13:36 UTC by naulan-chrzaszcz

2024-01-08 08:29 UTC, LiberiBg commented
Possible d'avoir le nombre de courses éffectuées par conducteur ?

2024-01-09 16:52 UTC, LiberiBg requested changes

2024-01-09 16:52 UTC, LiberiBg commented on src/api/controller/scoreboard/scoreboard.py
> +class ScoreboardRoutes(Blueprint):
Possible d'avoir pour les 3 routes :
Une liste de tous les users avec une note si aucun paramètre passé dans la requête
Si le paramètre est un driver_id, renvoyer le score de ce driver sous forme d'un objet (pas une liste)
pareil si le token est passé en paramètre (normalement les méthodes peuvent pas être appelé avec un token d'un passager mais raise l'exception dans le doute

2024-01-15 10:01 UTC, almerion requested changes

2024-01-15 10:30 UTC, almerion approved these changes
LGTM 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2024-01-15 10:31 UTC, merged