feat(auth): register mechanism - UC-33
DUT-Info-Montreuil/SAE-5.A-CarMate-Back pull request #5
Opened 2023-11-05 13:57 UTC by naulan-chrzaszcz

2023-11-13 19:49 UTC, almerion requested changes
Manque l'image pour vérifier si c'est bien un étudiant ou un professeur dans l'inscription

2023-11-13 19:49 UTC, almerion commented on src/api/controller/user/auth.py
> +        abort(400)
Il n'y a pas de vérif si les credential sont vides ? ça va planter s'ils sont vide non ?

2023-11-13 19:49 UTC, almerion commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
Pourquoi on hash le token, il est sensé être unique déjà non ? Et le hasher lui fait théoriquement perdre son unicité

2023-11-13 19:49 UTC, almerion commented on src/database/repositories/user_repository.py
> +                         VALUES (DEFAULT, %s, %s, %s, SHA512(%s), DEFAULT)
J'aurais préféré qu'on hash le mot de passe en dehors de la base de donnée histoire qu'on ait plus de contrôle dessus, mais si tu veut le laisser comme ça c'est pas si grave je suppose

2023-11-13 19:49 UTC, almerion commented on test/auth/test_register.py
> +            self.register.worker(credential)
On a pas de test pour les string trop longues, prénom et nom de famille ?

2023-11-13 20:15 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
Dans la base de données, on n'a pas besoin d'avoir le token en clair selon moi. Pourquoi ?
Car, si par purs malheurs, une personne malveillante a possession de la base de données. Si on laisse les tokens en clair (donc c'est-à-dire qu'ont les hashe pas) la personne malveillante aura accès à tous les comptes utilisateur (où le token est encore valide) ?

Avec quelque recherche sur les recommandations de la CNIL, il est vrai qu'il ne mentionne pas le hashage du jeton d'accès. 
Mais, je cite:
source: https://www.cnil.fr/fr/les-jetons-individuels-de-connexion-ou-token-access
> Dans ces conditions, il est nécessaire de mettre en œuvre des contre-mesures afin d’éviter l’accès non autorisé à des données personnelles.

Donc, est-ce que le hashage du Token est une contre-mesure afin d'éviter l'accès non autorisé à des données personnelles ?

2023-11-13 20:28 UTC, naulan-chrzaszcz commented on src/database/repositories/user_repository.py
> +                         VALUES (DEFAULT, %s, %s, %s, SHA512(%s), DEFAULT)
Le plus gros défaut de mon code, c'est qu'on voit le mot de passe en clair dans la requête.
Ta raison, je vais faire une fonction côté back pour hashé le mot de passe avant de l'input dans la database 🚀 🚀 🚀

2023-11-13 20:32 UTC, almerion commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
Je pense qu'à partir du moment ou un utilisateur non autorisé as accès à la db on a déjà perdu, il a déjà accès aux comptes et à leurs données, qu'il ait le token ou non c'est déjà game over puisque le token sert à donner accès ou non à certaines informations de la base de données.

S'il a accès à la base de donnée je pense que le hasher le token c'est comme un rideau de fils pour un chien, c'est le dernier de ses problèmes. 

Pauvre db, c'est pas gratuit les fonctions de hashage

2023-11-13 21:53 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
![](https://camo.githubusercontent.com/878a6bbfa5cb0f301d122a8ef593ea29ae6d12db8279c09eb124df2a161ac6c8/68747470733a2f2f696d6167652e6e6f656c736861636b2e636f6d2f66696368696572732f323031382f31302f312f313532303235363133342d726973697461737565322e706e67)

2023-11-14 17:52 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
Pour revenir à ce sujet, c'est plutôt si une personne intercepte les requêtes de la base de données c'est bien de les hashés

2023-11-14 17:52 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
Seul l'utilisateur aura le token en clair

2023-11-14 17:52 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
C'est pas si mal au final

2023-11-14 17:54 UTC, naulan-chrzaszcz commented on src/database/repositories/token_repository.py
> +                         VALUES (SHA512(%s), %s, %s)
C'est comme pour le mot de passe au final

2023-11-16 18:56 UTC, naulan-chrzaszcz commented
LGTM 🚀 🚀 🚀

2023-11-16 20:56 UTC, almerion requested changes
Manque une unique exception au niveau des tables student&teacher_license quand une image est déjà en base de donnée

2023-11-16 20:56 UTC, almerion commented on src/api/controller/user/auth.py
> +        credential = json.loads(request.form.get("credential"))
le front doit envoyer tout dans un json sous la forme: 
`{
credentials: {
email: ..., password: ..., ...
}
}` ? C'est pas plus simple de juste envoyer un json mais sans la clé credentials ?

2023-11-16 20:56 UTC, almerion commented on src/api/controller/user/auth.py
> +    if not all(document, "." in document.filename, document.filename .rsplit(".", 1)[1].lower() in IMAGE_FORMAT_ALLOWED_EXTENSIONS):
Cette ligne est assez indigeste, il y a moyen de mettre un commentaire au dessus pour expliquer ce qu'elle check, enfin de ce que j'ai compris c'est pour check l'extension du fichier mais j'ai un doute. Et il y a un espace entre `filename` et `.rsplit`, je ne suis pas trop sur que ce soit intentionel

2023-11-16 20:56 UTC, almerion commented on src/api/worker/auth/use_case/register.py
> +                    raise InternalServerError()
Je ne vois pas trop l'intérêt d'avoir deux except s'ils raise la même exception et log la même chose, autant juste except Exception je pense **

2023-11-16 20:56 UTC, almerion commented on src/api/worker/auth/use_case/register.py
> +                    raise InternalServerError()
idem **

2023-11-16 20:56 UTC, almerion commented on src/api/worker/auth/use_case/register.py
> +            raise InternalServerError()
idem ? Je commence a avoir un doute, si tu except Exception ça ne catch pas InternalServer ? **

2023-11-16 20:56 UTC, almerion commented on src/database/repositories/student_license_repository.py
> +                except lookup(errorcodes.INTERNAL_ERROR) | Exception as e:
ici aussi ? ignore ces review tu peux mettre en resolve si Exception ne catch pas internal server error **

2023-11-16 20:56 UTC, almerion commented on src/database/repositories/teacher_license_repository.py
> +                    raise InternalServer()
**

2023-11-16 20:56 UTC, almerion commented on src/database/repositories/token_repository.py
> -                    raise InternalServer(e)
**

2023-11-16 20:56 UTC, almerion commented on test/auth/test_register.py
> +            self.register.worker(credential, self.teacher_account_type, self.teacher_contract)
Pour tes tests, y'aurait moyen que quand ça ajoute quelque chose dans la db tu check dans le in memory repo que ce qui as été insert est bien égal à ce que tu as entré, idem pour le token que tu reçois si c'est bien le même qu'en db et le student & teacher license

2023-11-16 22:12 UTC, naulan-chrzaszcz commented on src/api/controller/user/auth.py
> +        credential = json.loads(request.form.get("credential"))
J'pense que ta pas compris comment fonctionne le `multipart/form-data` et comment le géré dans la route dans flask

Exemple avec un curl :
```
curl -X POST \
        -H "Content-Type: multipart/form-data" \
        -F "credential={\"key\":\"value\"}" \
        -F "document=@/path/to/your/file.jpg" \
        http://127.0.0.1:5000/auth/register
```

Exemple avec un front (source: ChatGPT) : 
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Upload Form</title>
</head>
<body>
    <h1>File Upload Form</h1>
    <form action="http://127.0.0.1:5000/auth/register" method="post" enctype="multipart/form-data">
        <label for="credential">Credential:</label>
        <input type="text" name="credential" id="credential" required>
        <br>
        <label for="document">Select File:</label>
        <input type="file" name="document" id="document" required>
        <br>
        <input type="submit" value="Upload">
    </form>
</body>
</html>
```

2023-11-16 22:31 UTC, naulan-chrzaszcz commented on test/auth/test_register.py
> +            self.register.worker(credential, self.teacher_account_type, self.teacher_contract)
Alors j'ai l'impression que tu ne peux pas dupliquer le document si tu utilise le worker register deux fois avec le même email

2023-11-16 22:31 UTC, naulan-chrzaszcz commented on test/auth/test_register.py
> +            self.register.worker(credential, self.teacher_account_type, self.teacher_contract)
UserRepository.insert va planté avant d'insert les licenses

2023-11-16 22:33 UTC, naulan-chrzaszcz commented on test/auth/test_register.py
> +            self.register.worker(credential, self.teacher_account_type, self.teacher_contract)
J'ai quand même prevu le coup côté DB et côté Mock mais j'ai pas l'impression qu'on passera dedans un jour ou l'autre pour le register

2023-11-16 22:34 UTC, naulan-chrzaszcz commented on test/auth/test_register.py
> +            self.register.worker(credential, self.teacher_account_type, self.teacher_contract)
Probablement pour d'autre route cela sera probable que le mec mets deux fois le même document

2023-11-16 23:22 UTC, almerion commented on src/api/controller/user/auth.py
> +        credential = json.loads(request.form.get("credential"))
heuuu non xD 
![image](https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Back/assets/95338528/8fabcc85-8952-4d5a-8d58-c2bd34829655)
![image](https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Back/assets/95338528/a57b2687-cfa7-4974-887f-614d13ef7721)
![image](https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Back/assets/95338528/927597ca-aa8b-4bcd-a4f4-4684a4776520)

2023-11-17 08:41 UTC, almerion approved these changes
LGTM :rocket::rocket::rocket::rocket:

2023-11-17 08:42 UTC, merged