fix(reserve-create-conflicts): fix conflicts between reservation and …
DUT-Info-Montreuil/SAE-5.A-carmate-back pull request #50
Opened 2024-01-09 13:39 UTC by almerion

…creation

2024-01-09 13:46 UTC, naulan-chrzaszcz requested changes
Babage

2024-01-09 13:46 UTC, naulan-chrzaszcz commented on src/database/repositories/booking_carpooling_repository.py
> +                    ON (rc.carpooling_id = c.id)
Pourquoi tu met des parenthèses

2024-01-09 13:46 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +            )
Code style

2024-01-09 13:46 UTC, naulan-chrzaszcz commented on src/database/repositories/propose_scheduled_carpooling.py
> +        has_conflict: bool = False
```suggestion
        has_conflict: bool
```

2024-01-09 13:46 UTC, naulan-chrzaszcz commented on src/mocks/carpooling/in_memory_carpooling_repository.py
> +                    and carpooling.is_canceled is False:
```suggestion
                    and not carpooling.is_canceled:
```

2024-01-09 13:46 UTC, naulan-chrzaszcz commented on test/carpooling/test_booking_carpooling.py
> +from hashlib import sha512
code style

2024-01-12 10:43 UTC, naulan-chrzaszcz requested changes
Review du code style

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on src/api/controller/carpooling/booking.py
> +    CredentialInvalid, BookingCanNotBeCreated
```suggestion
    CredentialInvalid,
    BookingCanNotBeCreated
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/booking_carpooling.py
> +    InternalServerError, BookingCanNotBeCreated
```suggestion
    InternalServerError,
    BookingCanNotBeCreated
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/booking_carpooling.py
> +from database.schemas import CarpoolingTable, PassengerProfileTable, Weekday, DriverProfileTable
```suggestion
from database.schemas import (
    CarpoolingTable,
    PassengerProfileTable,
    Weekday,
    DriverProfileTable
)
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on src/database/interfaces/token_repository_interface.py
> +    UserTable, PassengerProfileTable
```suggestion
    UserTable,
    PassengerProfileTable
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on src/mocks/user/in_memory_propose_scheduled_carpooling_repository.py
> +from database.schemas import PassengerScheduledCarpoolingTable, PassengerProfileTable, CarpoolingTable, Weekday
```suggestion
from database.schemas import (
    PassengerScheduledCarpoolingTable,
    PassengerProfileTable,
    CarpoolingTable,
    Weekday
)
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on test/carpooling/test_booking_carpooling.py
> +    CarpoolingNotFound, BookingCanNotBeCreated
```suggestion
    CarpoolingNotFound,
    BookingCanNotBeCreated
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on test/carpooling/test_create_carpooling.py
> +    PassengerScheduledCarpoolingTable, Weekday, ReserveCarpoolingTable, PassengerProfileTable
```suggestion
from database.schemas import (
    UserTable,
    TokenTable,
    DriverProfileTable,
    CarpoolingTable,
    PassengerScheduledCarpoolingTable,
    Weekday,
    ReserveCarpoolingTable,
    PassengerProfileTable
)
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/booking_carpooling.py
> +
```suggestion
```

2024-01-12 10:43 UTC, naulan-chrzaszcz commented on src/api/worker/carpooling/use_case/create_carpooling.py
> +
```suggestion
```

2024-01-12 10:47 UTC, naulan-chrzaszcz reviewed
Donc si je comprend bien, avant on pouvais reserver autant de fois qu'on veux de carpooling même si elle est déjà reservé par nous ?

2024-01-12 10:47 UTC, naulan-chrzaszcz commented on src/database/repositories/carpooling_repository.py
> +                )
```suggestion
            SELECT EXISTS(
                SELECT 1
                FROM carmate.{CARPOOLING_TABLE_NAME}
                WHERE driver_id=%s 
                    AND is_canceled=false
                    AND departure_date_time = to_timestamp(%s)
            )
```

2024-01-12 16:10 UTC, almerion commented
> Donc si je comprend bien, avant on pouvais reserver autant de fois qu'on veux de carpooling même si elle est déjà reservé par nous ?

Oui, enfin le problème principal c'était que on pouvait avoir 3 covoiturages le même jour à la même heure sans que l'api ne donne d'erreur mais du coup ce que tu as dit est fix par la même occasion avec cette pr

2024-01-14 16:56 UTC, naulan-chrzaszcz approved these changes
LGTM !!!!! 🚀

2024-01-14 17:21 UTC, merged