WIP
DUT-Info-Montreuil/SAE-5.A-CarMate-Back pull request #8
Opened 2023-11-13 19:41 UTC by LiberiBg

2023-11-14 13:05 UTC, naulan-chrzaszcz requested changes
J'ai verifier vite fait, essaye de modifier les trucs qui te semble ok

2023-11-14 13:05 UTC, naulan-chrzaszcz commented on src/database/repositories/user_repository.py
> +            raise InternalServer
Le try doit être moins gros, il doit faire max 1ligne

2023-11-14 13:05 UTC, naulan-chrzaszcz commented on test/auth/test_login.py
> +            self.login.worker(credential)
Alors c'est marrant mais faut rester neutre dans le code, met des noms qui n'existe pas

2023-11-14 13:05 UTC, naulan-chrzaszcz commented on test/mock/auth/in_memory_token_repository.py
> +        return in_memory_token
La fonction ne lève aucune exception ? Le mock n'est pas sensé ce comporter comme une base de données ?

2023-11-14 13:05 UTC, naulan-chrzaszcz commented on test/mock/user/in_memory_user_repository.py
> +                raise lookup(errorcodes.UNIQUE_VIOLATION)
C'est pas forcement toi, jdoit aussi faire pareil pour moi, mais faut mettre nos erreurs de DB

2023-11-14 13:05 UTC, naulan-chrzaszcz commented on test/mock/user/in_memory_user_repository.py
> +    users_counter: int = 0
Pareil ici, faut rester neutre

2023-11-14 13:19 UTC, LiberiBg commented on src/api/worker/auth/use_case/token.py
> +from src.api.worker.auth.interfaces import TokenInterface
Me suis dit qu'il valait mieux spécifier le chemin entier mais ma foi tant que ça marche

2023-11-14 13:22 UTC, LiberiBg commented on src/api/worker/user/exceptions.py
> +    pass
2 lignes entre chaques class c'est good ?

2023-11-14 13:25 UTC, LiberiBg commented on src/api/worker/user/models/repositories_interface/login_interfaces.pyi
Aucun soucis avec .pyi et j'ai pas accès à ton resgiter_interface ptet que tu l'as pas push

2023-11-14 13:28 UTC, LiberiBg commented on src/api/worker/user/use_case/login.py
> +            raise EmailFormatInvalid
On fait un refactor plus tard ? Ou on voit ça ce soir

2023-11-14 13:31 UTC, LiberiBg commented on test/mock/auth/in_memory_token_repository.py
> +        return in_memory_token
J'ai pas relu ton code je t'avoue

2023-11-14 13:42 UTC, LiberiBg commented on src/api/worker/user/use_case/login.py
> +        except Exception:
Hmmm pas compris, pour la création du token j'ai besoin d'un UserTable de la personne essayant de se connecter non ? J'me suis basé sur ta méthode TokenRepository.insert

2023-11-14 13:44 UTC, LiberiBg commented on src/api/worker/user/use_case/login.py
> +    #@staticmethod
Pour donner un UserRepo et un TokenRepo au moment de la construction (a du sens pour les tests unitaires selon moi)

2023-11-14 17:43 UTC, naulan-chrzaszcz commented on src/api/worker/user/exceptions.py
> +    pass
> 2 lignes entre chaques class c'est good ?

https://peps.python.org/pep-0008/#blank-lines

2023-11-14 17:49 UTC, naulan-chrzaszcz commented on test/mock/auth/in_memory_token_repository.py
> +        return in_memory_token
Tkt, j'vais fix ca

2023-11-14 23:04 UTC, naulan-chrzaszcz requested changes
Pas mal de chose a revoir sur ta branche mais ca ma permit de voir ce que je peux aussi modifier sur ma branche

2023-11-14 23:04 UTC, naulan-chrzaszcz commented on src/api/worker/user/use_case/login.py
> +    def worker(self, credential: CredentialDTO) -> TokenDTO:
```suggestion
    def worker(self, credential: CredentialDTO) -> TokenDTO:
        """
        Documentez la fonction
        """
```
Faut que je le fasse aussi pour ma PR

2023-11-14 23:04 UTC, naulan-chrzaszcz commented on src/api/worker/user/use_case/login.py
> +        except Exception:
Tu couvre pas toute les erreurs

2023-11-14 23:04 UTC, naulan-chrzaszcz commented on src/database/repositories/user_repository.py
> +                raise NotFound
A tester

2023-11-14 23:04 UTC, naulan-chrzaszcz commented on test/mock/user/in_memory_user_repository.py
> +        raise NotFound
Je ne sais pas si j'ai fait comme ca, mais il y a pas dans python un `.contains` ? (A verifier)

2023-11-14 23:05 UTC, naulan-chrzaszcz commented on src/api/worker/user/use_case/login.py
> +    #@staticmethod
Je parle de `    #@staticmethod`

2023-11-14 23:06 UTC, naulan-chrzaszcz commented on src/api/worker/user/use_case/login.py
> +            raise EmailFormatInvalid
On peut faire un refactor plus tard sur la branche feature/auth

2023-11-20 08:05 UTC, naulan-chrzaszcz requested changes
Les derniers trucs avant le merging

2023-11-20 08:05 UTC, naulan-chrzaszcz commented on src/api/controller/user/auth.py
> +        abort(415)
```suggestion
    if not request.is_json:
        abort(415)
    
    credential: CredentialDTO
    json_data = None
    token = None
```

2023-11-20 08:05 UTC, naulan-chrzaszcz commented on src/api/controller/user/auth.py
> +    )
```suggestion
    credential = CredentialDTO("", "", json_data.get("email_address"), json_data.get("password"))
```

2023-11-20 20:11 UTC, LiberiBg commented on test/auth/test_login.py
> +        with self.assertRaises(Exception) as context:
sans le as context ça marche plus lol

2023-11-21 08:18 UTC, naulan-chrzaszcz reviewed
Vérifier certaine chose dans le code mais sinon ça m'a l'air d’être OK
Dit moi quand ta tester pour que je puisse approver 👌

2023-11-21 08:18 UTC, naulan-chrzaszcz commented on src/api/controller/user/auth.py
> +        abort(500)
Donc si je met un content-type sur application/json et que je met dans le corp de ma requête '"login": "admin", "password": "pwd"}' (j'ai enlever le '{') ça sera une erreur 500 ?
J'pense que c'est une autre code d'erreur qui faut renvoyer

2023-11-21 08:18 UTC, naulan-chrzaszcz commented on src/api/controller/user/auth.py
> +        abort(400)
Cette condition fonctionne ? Ta tester ?

2023-11-21 22:58 UTC, merged